### PR TITLE
Updates for video.js 5.0 compatibility

### PR DESCRIPTION
**Pull request by misteroneill**

### CODE REVIEW

**Comment by forbesjo** [comment]
It looks like we're overwriting video.js's logging functions, should we remove it for 5.0?

https://github.com/brightcove/videojs-debugger/pull/2/files#diff-bd07b5bc9e2be61132ef8c82fa62242bL340

**Comment by gkatsev** [comment]
We should wrap the videojs functions instead. When we first created this, videojs didn't have these functions.

**Comment by misteroneill** [comment]
Cool, I'll make that change!

**Comment by misteroneill** [comment]
Looks like @forbesjo did it. :+1:

**Pull request merged**
