### PR TITLE
Reorder history logger

### PR DESCRIPTION
**Pull request by misteroneill**

### CODE REVIEW

**Comment by gkatsev** [comment]
Also, we probably should wrap the native videojs logging functions (now that they exist), instead of overwriting them.

**Comment by misteroneill** [comment]
@gkatsev That sounds reasonable, but probably for another PR. This is mainly an effort to get work that was done on the old private repo into this one.

**Comment by gkatsev** [comment]
Sounds good.

**Comment by forbesjo** [comment]
Needs a rebase now, this PR should make the tests pass.

**Pull request closed without merging**
